name: Robô TSB

on:  
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch: #Permite rodar manualmente clicando num botão no GitHub
      

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-bot:
    runs-on: ubuntu-latest 

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar bibliotecas
        run: pip install -r requirements.txt

      - name: Executar o Robô
        env:
          TZ: America/Sao_Paulo
          LANG: pt_BR.UTF-8
          LC_ALL: pt_BR.UTF-8
          GITHUB_ACTIONS: "true"
          PYTHONIOENCODING: "utf-8"
          PYTHONUNBUFFERED: "1"
          # Lendo das Variables
          ID_PLANILHA_GSHEET: ${{ vars.ID_PLANILHA_GSHEET }}
          ID_PLANILHA_ATT_GSHEET: ${{ vars.ID_PLANILHA_ATT_GSHEET }}
          ID_PASTA_DRIVE_FINAL: ${{ vars.ID_PASTA_DRIVE_FINAL }}
          # Lendo das Secrets
          TOKEN_ZUQ: ${{ vars.TOKEN_ZUQ }}
          LOGIN_GPM: ${{ vars.LOGIN_GPM }}
          SENHA_GPM: ${{ vars.SENHA_GPM }}
          ID_PLANILHA_CONTROLE: ${{ vars.ID_PLANILHA_CONTROLE }}
          NOME_ABA_CONTROLE: ${{ vars.NOME_ABA }}
          CELULA_DATA_CONTROLE: ${{ vars.CELULA_DATA }}

          # Lendo das Secrets
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python main.py
        
